<form class="form" action="<?php echo $this->getFormAction(); ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>" />

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Form') ?></span></legend><br>
        <div class="field required">
            <label for="number" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span>
            </label>

            <div class="control">
                <input name="number" type="text" value="" />
            </div>
        </div>

        <div class="field required">
            <label for="email" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Email ID') ?></span>
            </label>

            <div class="control">
                <input name="email" type="email" value="" />
            </div>
        </div>


        <div class="field required">
            <label for="message" class="label">
                <span><?php /* @escapeNotVerified */ echo __('What in your mind?') ?></span>
            </label>

            <div class="control">
                <input name="message" type="text" value="" placeholder="Your message"/>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>